name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_DIR: ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/build

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.system.os }}

    strategy:
      fail-fast: false
      matrix:
        system:
          - os: ubuntu-latest
            generator: Ninja
          - os: windows-latest
          - os: macos-13
            generator: Ninja
          - os: macos-latest
            generator: Ninja
        build_type:
          - Release
    env:
      CMAKE_GENERATOR: ${{ matrix.system.generator }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

#      - name: Get number of CPU cores
#        uses: SimenB/github-actions-cpu-cores@v2
#        id: cpu-cores
#      - name: Set CMake Parallel level
#        run: |
#          echo "CMAKE_BUILD_PARALLEL_LEVEL=${{ steps.cpu-cores.outputs.count }}" >> ${GITHUB_ENV}
#          echo "CTEST_PARALLEL_LEVEL=1" >> ${GITHUB_ENV}

      - name: Install system deps (Linux)
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo apt-get update
          sudo apt-get -y install ninja-build uuid-dev

      - name: Install system deps (macOS)
        if: ${{runner.os == 'macOS'}}
        run: |
          brew install ninja

      #######################
      # BUILD
      #######################
      - name: Configure CMake
        run: >
          cmake
          -B "${BUILD_DIR}"
          -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S "${{ github.workspace }}"
          -DBUILD_TESTING=On
          -DBUILD_PACKAGE=On

      - name: Build
        run: cmake --build "${BUILD_DIR}" --config ${{ matrix.build_type }}

      #######################
      # TEST
      #######################
      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test_results_${{runner.os}}
          path: ${{env.BUILD_DIR}}/Testing/Temporary/LastTest.log

      #######################
      # PACKAGE
      #######################
      - name: Package
        working-directory: ${{env.BUILD_DIR}}
        run: cpack -B "${BUILD_DIR}/packages"

      - name: Upload failed package artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: failed_package_${{runner.os}}
          path: ${{env.BUILD_DIR}}/packages

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages_${{runner.os}}_${{runner.arch}}
          path: ${{env.BUILD_DIR}}/packages/*.*
          if-no-files-found: error
